steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_IMAGE_NAME}:test',
    '-f', 'Dockerfile',
    '--target', 'dev',
    '.',
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'run',
    '--rm',
    '--entrypoint', 'py.test',
    '${_IMAGE_NAME}:test',
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_IMAGE_NAME}:${TAG_NAME}',
    '-t', '${_IMAGE_NAME}:latest',
    '-f', 'Dockerfile',
    '--target', 'prod',
    '.',
  ]

images:
  - '${_IMAGE_NAME}:${TAG_NAME}'
  - '${_IMAGE_NAME}:latest'

timeout: 600s
substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/github.com/globalfishingwatch/pipe-segment'
options:
  dynamic_substitutions: true

