services:
  dev:
    image: gfw/pipe-segment
    entrypoint: "./scripts/run.sh"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
  gcloud:
    image: google/cloud-sdk:latest
    entrypoint: gcloud
    volumes:
      - "gcp:/root/.config/"

# Use an external named volume so that we can share gcp auth across containers
# Before first use, this volume must be manually created with
#   docker volume create --name=gcp
volumes:
  gcp:
    external: true