services:
  dev:
    image: gfw/pipe-segment-dev
    build:
      context: .
      target: dev
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: /bin/bash

  test:
    image: gfw/pipe-segment-test
    environment:
      BIGQUERY_HOST: bigquery
      INTEGRATION_TESTS: true
    build:
      context: .
      target: test
    entrypoint: "pytest -v"
    depends_on:
      - bigquery

  bigquery:
    platform: linux/x86_64
    ports:
      - 9050:9050
    image: ghcr.io/goccy/bigquery-emulator:latest
    command: --project=test_project --dataset=test_dataset

# Volume to hold GCP authentication
volumes:
  gcp:
    external: true
