FROM gcr.io/world-fishing-827/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8

# Setup scheduler-specific dependencies
COPY ./requirements/scheduler.txt ./
RUN pip install -r scheduler.txt

# Temporary. TODO: Use a test docker image with extra dependencies.
COPY ./requirements/test.txt ./
RUN pip install -r test.txt

# Temporary. TODO: Use a dev docker image with extra dependencies.
COPY ./requirements/dev.txt ./
RUN pip install -r dev.txt

# Setup local packages
COPY . /opt/project
RUN pip install -e .

# To properly run Makefile
RUN apt install -y bsdmainutils 

# Setup the entrypoint for quickly executing the pipelines
ENTRYPOINT ["scripts/run.sh"]

